/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Team = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sharedBookmarks' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
});
export const TerminalSession = IDL.Record({
  'id' : IDL.Text,
  'lastUsedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'outputHistory' : IDL.Vec(IDL.Text),
  'lastSavedAt' : IDL.Int,
  'commandHistory' : IDL.Vec(IDL.Text),
  'workingDirectory' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTeamBookmark' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'appendOutput' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearGitHubPAT' : IDL.Func([], [], []),
  'clearNotifications' : IDL.Func([], [], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Text], [Team], []),
  'deleteTerminalSession' : IDL.Func([IDL.Text], [], []),
  'getCachedData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGitHubPAT' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getTeamBookmarks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getTeamMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadTerminalSessions' : IDL.Func([], [IDL.Vec(TerminalSession)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'removeTeamBookmark' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGitHubPAT' : IDL.Func([IDL.Text], [], []),
  'saveTerminalSession' : IDL.Func([TerminalSession], [], []),
  'setCachedData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCommandHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Team = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sharedBookmarks' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
  });
  const TerminalSession = IDL.Record({
    'id' : IDL.Text,
    'lastUsedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'outputHistory' : IDL.Vec(IDL.Text),
    'lastSavedAt' : IDL.Int,
    'commandHistory' : IDL.Vec(IDL.Text),
    'workingDirectory' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTeamBookmark' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'appendOutput' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearGitHubPAT' : IDL.Func([], [], []),
    'clearNotifications' : IDL.Func([], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text], [Team], []),
    'deleteTerminalSession' : IDL.Func([IDL.Text], [], []),
    'getCachedData' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGitHubPAT' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getTeamBookmarks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getTeamMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadTerminalSessions' : IDL.Func(
        [],
        [IDL.Vec(TerminalSession)],
        ['query'],
      ),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'removeTeamBookmark' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGitHubPAT' : IDL.Func([IDL.Text], [], []),
    'saveTerminalSession' : IDL.Func([TerminalSession], [], []),
    'setCachedData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCommandHistory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };