/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookmarkID = IDL.Text;
export const Note = IDL.Text;
export const Tag = IDL.Text;
export const BookmarkEntry = IDL.Record({
  'repoId' : BookmarkID,
  'note' : IDL.Opt(Note),
  'tags' : IDL.Vec(Tag),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkBookmark' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(BookmarkEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyGithubToken' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Text], [], []),
  'removeMyGithubToken' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMyGithubToken' : IDL.Func([IDL.Text], [], []),
  'updateBookmarkNote' : IDL.Func([IDL.Text, IDL.Opt(Note)], [], []),
  'updateBookmarkTags' : IDL.Func([IDL.Text, IDL.Vec(Tag)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookmarkID = IDL.Text;
  const Note = IDL.Text;
  const Tag = IDL.Text;
  const BookmarkEntry = IDL.Record({
    'repoId' : BookmarkID,
    'note' : IDL.Opt(Note),
    'tags' : IDL.Vec(Tag),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkBookmark' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(BookmarkEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyGithubToken' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Text], [], []),
    'removeMyGithubToken' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMyGithubToken' : IDL.Func([IDL.Text], [], []),
    'updateBookmarkNote' : IDL.Func([IDL.Text, IDL.Opt(Note)], [], []),
    'updateBookmarkTags' : IDL.Func([IDL.Text, IDL.Vec(Tag)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };